using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class CameraControls : MonoBehaviour
{
    private Transform player;
    public float distance = 10.0f;
    public float cameraSpeed = 5.0f;

    // Start is called before the first frame update
    void Start()
    {
        player = GameObject.FindGameObjectWithTag("Player").transform;
    }

    // Update is called once per frame
    void Update()
    {
        //transform.position = player.position + (Vector3.up * distance);
        if(player != null)
        {
            transform.position = Vector3.Lerp(transform.position, player.position + (Vector3.up * distance), Time.deltaTime * cameraSpeed);
        }


    }
}
