using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerRotation : MonoBehaviour
{
    public Camera playerCamera;
    public GameObject bullet;
    public Transform muzzle;
    public AudioSource gunShot;
    public Animator gunAnimation;

    // Start is called before the first frame update
    void Start()
    {
        
    }

    // Update is called once per frame
    void Update()
    {
        Ray ray = playerCamera.ScreenPointToRay(Input.mousePosition);
        RaycastHit hit;

        if(Physics.Raycast(ray, out hit))
        {
            Vector3 lookAtPoint = new Vector3(hit.point.x, transform.position.y, hit.point.z);
            
            transform.LookAt(lookAtPoint);
        }
        if (Input.GetMouseButtonDown(0))
        {
            gunAnimation.SetTrigger("Shoot");
            gunShot.Play();
        }
    }

